FROM node:24 AS api-development
RUN mkdir /srv/backend
WORKDIR /srv/backend
RUN mkdir -p node_modules
COPY backend/package.json backend/yarn.lock ./
RUN yarn install --pure-lockfile
COPY backend/. .
COPY shared/ /srv/shared/

FROM node:24 AS api-test
RUN mkdir /srv/backend
WORKDIR /srv/backend
COPY backend/package.json backend/yarn.lock ./
RUN yarn install --silent
RUN mkdir -p node_modules

FROM node:24-slim AS api-production
EXPOSE 4000
USER node
WORKDIR /srv/backend
COPY --from=api-development /srv/backend/node_modules ./node_modules
COPY --from=api-development /srv/shared/ /srv/shared/
COPY backend/. .
CMD ["npm", "run", "dev"]