FROM node:14.11.0 AS api-builder
RUN mkdir /srv/backend
WORKDIR /srv/backend
RUN mkdir -p node_modules
COPY package.json yarn.lock ./
RUN yarn install --pure-lockfile
COPY . .

FROM node:14.11.0-slim AS api-production
EXPOSE 4000
USER node
WORKDIR /srv/backend
COPY --from=api-builder /srv/backend/node_modules ./node_modules
COPY . .
CMD ["npm", "run", "start"]
