FROM node:14.17.6 AS api-development
RUN mkdir /srv/backend
WORKDIR /srv/backend
RUN mkdir -p node_modules
COPY package.json yarn.lock ./
RUN yarn install --pure-lockfile
COPY . .

FROM node:14.17.6-slim AS api-production
EXPOSE 4000
USER node
WORKDIR /srv/backend
COPY --from=api-development /srv/backend/node_modules ./node_modules
COPY . .
CMD ["npm", "run", "start"]
