name: 'Bug Report'
description: 'Bug report HackforLA issue form.'

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: Clearly state the bug
    validations:
      required: true
  - type: dropdown
    id: feature
    attributes:
      label: Feature
      description: Select a feature related to the bug
      options:
        - AWS
        - Brand
        - Login
        - Users
        - Agenda
        - Check in
        - Database
        - Dashboard
        - Marketing
        - Onboarding
        - Repo Update
        - Documentation
        - GitHub Actions
        - GitHub Hygiene
        - Infrastructure
        - Package Update
        - ESLint Warnings
        - Form validation
        - Recurring Events
        - Project Management
        - Account Setup Automation
        - Meeting Time Change Ticket
        - Add/Remove PM access
    validations:
      required: true
  - type: textarea
    id: replicate
    attributes:
      label: How to Replicate
      description: Clearly state how to replicate the bug
    validations:
      required: true
  - type: dropdown
    id: notification
    attributes:
      label: Request notification after bug squashing
      description: Request notification after a bug is squashed
      options:
        - Yes
        - No
    validations:
      required: true
  - type: textarea
    id: resource
    attributes:
      label: Resources/Information
      description: Include any important resources/information